export const DEFAULT_CATEGORIES = [
  { group_name: "Życie codzienne", name: "Zakupy spożywcze", icon: "🛒", color: "#f59e0b", sort_order: 10, kind: "expense" },
  { group_name: "Życie codzienne", name: "Restauracje", icon: "🍽️", color: "#d97706", sort_order: 11, kind: "expense" },
  { group_name: "Życie codzienne", name: "Chemia / higiena", icon: "🧼", color: "#ea580c", sort_order: 12, kind: "expense" },
  { group_name: "Zobowiązania", name: "Czynsz / kredyt", icon: "🏠", color: "#8b5cf6", sort_order: 20, kind: "expense" },
  { group_name: "Zobowiązania", name: "Media", icon: "💡", color: "#7c3aed", sort_order: 21, kind: "expense" },
  { group_name: "Zobowiązania", name: "Internet / telefon", icon: "📶", color: "#6d28d9", sort_order: 22, kind: "expense" },
  { group_name: "Zobowiązania", name: "Ubezpieczenia", icon: "🛡️", color: "#5b21b6", sort_order: 23, kind: "expense" },
  { group_name: "Transport", name: "Paliwo", icon: "⛽", color: "#3b82f6", sort_order: 30, kind: "expense" },
  { group_name: "Transport", name: "Komunikacja", icon: "🚌", color: "#2563eb", sort_order: 31, kind: "expense" },
  { group_name: "Zdrowie", name: "Apteka / lekarz", icon: "💊", color: "#ef4444", sort_order: 40, kind: "expense" },
  { group_name: "Rozrywka", name: "Hobby", icon: "🎮", color: "#ec4899", sort_order: 50, kind: "expense" },
  { group_name: "Rozrywka", name: "Subskrypcje", icon: "📺", color: "#db2777", sort_order: 51, kind: "expense" },
  { group_name: "Osobiste", name: "Ubrania", icon: "👕", color: "#14b8a6", sort_order: 60, kind: "expense" },
  { group_name: "Oszczędności", name: "Fundusz awaryjny", icon: "🏦", color: "#0d9488", sort_order: 70, kind: "expense" },
  { group_name: "Oszczędności", name: "Cele", icon: "🎯", color: "#0f766e", sort_order: 71, kind: "expense" },
];
